add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = ">"     # The "symbol" segment is being set to "âœ"

prompt_order=["line_break","package","line_break","character","battery"]

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[directory]
style = "fg:fg"

[git_branch]
symbol = ""
truncation_length = 8
truncation_symbol = "..."
